### ISSUE TITLE
No resources found in argocd namespace after successful deploy

### ISSUE THREAD

**Issue by alarys** [garutilorenzo/k3s-oci-cluster#36]
Hi,

What a great guide and easy to follow terraform! I got things up and going quite quickly.

However, when I tried to do "kubectl get pods -n argocd" from the root user of a server node, I got "No resources found in argocd namespace". Doing a get pods -A also showed no argocd pods.

When I searched in the output of "terraform apply" I didn't see any reference to installing ArgoCD. I also checked the documentation and the default is to install ArgoCD.

I imagine I'm missing something simple?

**Comment by jameswmcnab** [comment]
I haven't got this far yet due to OCI capacity issues, but I believe argocd should be deployed (if `install_argocd: true`) by this script:

https://github.com/garutilorenzo/k3s-oci-cluster/blob/master/files/k3s-install-server.sh#L450-L459

This script is executed on the server pool instances via [cloudinit](https://cloudinit.readthedocs.io/en/latest/topics/format.html) as defined here:

https://github.com/garutilorenzo/k3s-oci-cluster/blob/master/data.tf#L6-L40

This is included in the instance template for the server pool instances here: https://github.com/garutilorenzo/k3s-oci-cluster/blob/master/template.tf#L51

**Comment by alarys** [comment]
Thank you, I'll deploy fresh with terraform again and make sure install_argocd: true is set.

I'll also try to manually install it after with the steps in the script to see if there are any errors, and let you know.

**Comment by jameswmcnab** [comment]
If you still have your instances you can SSH to them and check the cloudinit log file for the output of the scripts I referenced above, it lives at `/var/log/cloud-init-output.log`

**Comment by garutilorenzo** [comment]
Hi guys,

@alarys if argocd is not installed and install_argocd is set to true, follow @jameswmcnab tip check the cloudinit log file.
Maybe there is some error on the installation script

**Comment by alarys** [comment]
Hi,

Thanks for the info. I don't know what happened the first time around with no argo-cd pods running. Unfortunately, I had already destroyed that environment and don't have the cloud-init-output.log anymore. I'm going to close this.

Thanks!
